### ISSUE TITLE
ErrorException:strpos() Non-string needles will be interpreted as strings in the future

### ISSUE THREAD

**Issue by eddycek** [keboola/aws-s3-writer#4]
`docker-compose run --rm dev
[2019-10-10 17:32:36] CRITICAL: ErrorException:strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior {"errFile":"/code/vendor/symfony/config/Definition/BaseNode.php","errLine":502,"errCode":0,"errTrace":"#0 [internal function]: Keboola\\Component\\BaseComponent::Keboola\\Component\\{closure}(8192, 'strpos(): Non-s...', '/code/vendor/sy...', 502, Array)\n#1 /code/vendor/symfony/config/Definition/BaseNode.php(502): strpos('AKIAQ4QRYXTAFZY...', NULL)\n#2 /code/vendor/symfony/config/Definition/BaseNode.php(344): Symfony\\Component\\Config\\Definition\\BaseNode::resolvePlaceholderValue('AKIAQ4QRYXTAFZY...')\n#3 /code/vendor/symfony/config/Definition/ArrayNode.php(301): Symfony\\Component\\Config\\Definition\\BaseNode->normalize('AKIAQ4QRYXTAFZY...')\n#4 /code/vendor/symfony/config/Definition/BaseNode.php(368): Symfony\\Component\\Config\\Definition\\ArrayNode->normalizeValue(Array)\n#5 /code/vendor/symfony/config/Definition/ArrayNode.php(301): Symfony\\Component\\Config\\Definition\\BaseNode->normalize(Array)\n#6 /code/vendor/symfony/config/Definition/BaseNode.php(368): Symfony\\Component\\Config\\Definition\\ArrayNode->normalizeValue(Array)\n#7 /code/vendor/symfony/config/Definition/Processor.php(35): Symfony\\Component\\Config\\Definition\\BaseNode->normalize(Array)\n#8 /code/vendor/symfony/config/Definition/Processor.php(52): Symfony\\Component\\Config\\Definition\\Processor->process(Object(Symfony\\Component\\Config\\Definition\\ArrayNode), Array)\n#9 /code/vendor/keboola/php-component/src/Config/BaseConfig.php(43): Symfony\\Component\\Config\\Definition\\Processor->processConfiguration(Object(Keboola\\S3Writer\\ConfigDefinition), Array)\n#10 /code/vendor/keboola/php-component/src/Config/BaseConfig.php(34): Keboola\\Component\\Config\\BaseConfig->setConfig(Array)\n#11 /code/vendor/keboola/php-component/src/BaseComponent.php(82): Keboola\\Component\\Config\\BaseConfig->__construct(Array, Object(Keboola\\S3Writer\\ConfigDefinition))\n#12 /code/vendor/keboola/php-component/src/BaseComponent.php(43): Keboola\\Component\\BaseComponent->loadConfig()\n#13 /code/src/run.php(13): Keboola\\Component\\BaseComponent->__construct(Object(Keboola\\Component\\Logger))\n#14 {main}","errPrevious":""} []
`

**Comment by eddycek** [comment]
@ondrejhlavacek tohle se mi děje při spouštění přes `docker-compose run --rm dev`

**Comment by eddycek** [comment]
V dockerfile je `FROM php:7-cli`, takže proto.  Build jsem měl pod 7.3, pošlu fix. Btw zajímavé je, že jsem to zjistil až po delší době, protože testy jsou zelené (netestuje se celá aplikace). V tom jsou dobré datadir-tests, na těch bych to zjistil při prvním spuštění testů a ne až při manuálním spuštění appky.
